### ISSUE TITLE
Switch to rkyv & rkyv-codec

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/sendme#10]
I had a version that used `rkyv-codec` before, but threw it out due to it not being available on stable rust & some issues I had with `rykv`. But those should be fixable and would give us a better baseline for the protocol format

- https://docs.rs/rkyv_codec
- https://docs.rs/rkyv

**Comment by rklaehn** [comment]
Why?

I measured the performance of bincode, some other serde based codecs when building quic-rpc. I never found bincode to be a limiting factor for blob heavy formats.

Even according to the benchmarks on the rkyv site https://david.kolo.ski/blog/rkyv-is-faster-than/ it is just some percentage faster than fast serde based codecs such as bincode, not a factor of 2 or anything.

Where rkyv shines is when you want to grab data from a memory mapped file with zero copy, like you would e.g. for game assets. But for network code I don't think it is worth the additional complexity.

The way I see it you either do serde and eat the slight overhead, or you manually mangle Bytes to get true zero copy. Rkyv is somewhere in between.

**Comment by dignifiedquire** [comment]
This is mostly about the codec & length prefixing, the code is very manual atm, which is unfortunate. Speedwise postcard + `serde(borrow)` is fast enough, but the standard length prefix codecs force us to have copies which I want to avoid.

**Comment by rklaehn** [comment]
I find that for networking code, rkyv adds a lot of complexity over something from serde while not getting you all the way to true zero copy nirvana.

E.g. you got a Bytes from somewhere. Now you want to send it over the network. The only way I can see to make this truly zero copy is to first manually send the length prefix, then send the bytes.

```rust
sender.send_all(&(bytes.len() as u32).to_be_bytes()).await?;
sender.send_all(&bytes).await?;
```

Same on the recv side: you get a `Bytes` that just happens to contain the message and the length prefix, e.g. because you use http2 and you are lucky that 1 frame = 1 msg.

You want to produce something that is unburdened by lifetimes so you can send it somewhere else.

To do zero copy you have to manually create a subslice from your bytes, or use serde::deserialize followed by some code that converts &[u8] back into subslices of the original Bytes using https://docs.rs/bytes/latest/bytes/struct.Bytes.html#method.slice_ref

I don't see how rkyv helps with any of this.

**Comment by dignifiedquire** [comment]
this piece makes that a little nicer: https://github.com/zyansheep/rkyv_codec

**Comment by rklaehn** [comment]
Still not convinced that this is the way to go, given that we are limited so much by quic that it would probably be quite hard to even measure the difference.

But that is kinda neat...

**Comment by ramfox** [comment]
Interesting 3 part blog post about a foray into zero copy work: https://manishearth.github.io/blog/2022/08/03/zero-copy-1-not-a-yoking-matter/

Mentions wanting to use postcard + serde + cow in a zero-copy way

**Comment by ramfox** [comment]
@dignifiedquire can we close this issue?

**Comment by dignifiedquire** [comment]
lets close it for now
