### ISSUE TITLE
tempfiles are not cleaned up

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/sendme#102]
If you download a single file with output folder `foo`, and cancel the transfer halfway through, the tempfile is inside of the `foo` directory and is not deleted, but stays around.

**Comment by dignifiedquire** [comment]
Look like the reason is that we are using `NamedTempFile`s:

@flub I believe you wrote this code initially, thoughts?

https://docs.rs/tempfile/latest/tempfile/struct.NamedTempFile.html#resource-leaking

**Comment by flub** [comment]
Yeah, the reason for `NamedTempFile` is that I wanted to write the tempfile to the same directory as the final output is going to be.  Because if you write it to a global "tmp" on desktop machines you will often have to move between filesystems when moving it to the final output directory, and that involves copying all the data again instead of updating a dirent struct.  (It is my understanding that on mobile this is somewhat different: there is a per-app tmp usually though I'm not sure if they have same-fs guarantees or not)

The main problem is indeed that you need to have the rust destructors run.

On unix at least it would be possible to do the tempfile the correct way while still doing this in out output directory.  But I've always assumed that the tempfile crate does not expose this because it is not portable.

One way to mostly solve this is to add a ctrl-c handler.  Even if we don't do this while attempting graceful shutdown (because we're still unsure what that means and how to do that nicely, see #107 ) only adding the handler would ensure we can run rust destructors.

However we still leave temp files around when you kill the app outside of what ctrl-c can capture.  I'm not sure how to solve this other than get rid of the tempfile stuff entirely.

Looking at how bittorrent clients approach this might be worthwhile:

In my experience they write to the output directory under the final name with an extra suffix.  They do not attempt to clean up this file, but crucially will reuse it when restarted.

**Comment by dignifiedquire** [comment]
I likke the suffix approach 👍

**Comment by ramfox** [comment]
discord convo conclusions:
- use `ctrl-c` to clean up until we have a method for resuming downloads. This isn't a perfect solution (leaves temp files when `ctrl-c` is not used), but it at least ensures a clean experience when there is a clean shutdown.
- keep `NamedTempFile` as is, rather than using the suffix approach for now
