### ISSUE TITLE
Use CIDs in the frontend

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/sendme#14]
- use the prefix Cidv1 - Raw Codec - Blake3 256
- only use it in and output, not internally
- allow for blake3 hashes without cid prefix to still be used

**Comment by rklaehn** [comment]
Why are we doing this? We are adding an additional dependency and a somewhat confusing library.

Sendme is going to be ephemeral. Nobody is ever going to put a sendme hash into an URL or something. So I question if we should do this. Just use a 32 byte blake3 hash and be done with it, and if we ever switch away from blake3 we just change it on both sides.

**Comment by dvc94ch** [comment]
Agree that the cid stuff from ipfs is poorly designed.

1. if you have a version prefix you don't need the multibase/multihash stuff, since the base/hash can be determined by the version prefix. if you care about perf, base64 is pretty much your only option as there aren't 128 printable ascii characters. I tend to use the url safe alphabet.
2. the ipld codec is completely useless for most applications. a much better approach in my opinion would be providing a mime type. using the mime type you can find an application to open it, browsers and other applications know how to use a mime type and if you build a http server at some point you can serve the file with the correct mime type
3. if you want to support streaming in the future you should include the length of the file in the content identifier.

**Comment by rklaehn** [comment]
Closed by #123
