### ISSUE TITLE
Serialise blobs without loading them entirely into memory

### ISSUE THREAD

**Issue by flub** [n0-computer/sendme#42]
Currently serialisation results in writing the serialised blob entirely into memory before starting to send it out on the wire.  This is a problem for sending larger files on reasonably constrained devices.  We should figure out how to start sending bytes before the entire blob is serialised.

**Comment by rklaehn** [comment]
This is related to https://github.com/n0-computer/sendme/issues/33

Basically we want to send and receive incrementally. I think sending incrementally is best done using the bao SliceExtractor, even if we want to send the entire file.

Basically you give it Seek+Read access to both the outboard and the file, and it gives you a Read from which you can pull chunks to send over the wire.

For the send side I think we could just use a tokio task that does that (pull from read, send async, in a loop, until it is done).

For the recv side it is trickier, which is why I am working on a proper async SliceDecoder.

**Comment by rklaehn** [comment]
The code would look something like this:

```rust
let encoder = SliceExtractor::new_outboard(data_file, outboard_file, 0, len);
tokio::spawn(async {
  let buffer = [0u8; 1024];
  loop {
    let read = encoder.read(&mut buffer)?;
    if read == 0 {
      break;
    }
    socket.send(&buffer[..read]).await?;
  }
});
```

So reading from outboard and data file would still be sync, but it would happen in a tokio task that can be run on the blocking pool....

**Comment by dignifiedquire** [comment]
this is not the case anymore in my pr, we just load the data into memory to calculate the hash + outboard data.

**Comment by flub** [comment]
Oh yeah, I misread the protocol...
