### ISSUE TITLE
No error if file got deleted on the sender side

### ISSUE THREAD

**Issue by link2xt** [n0-computer/sendme#9]
I downloaded sendme 0.2.3 and ran `sendme provide screenshot.jpg`.

Then when I removed the file and tried to get it, I got no error, simply nothing is downloaded silently.

Then I recreated empty file with `touch screenshot.jpg`. Then receiver side started to show "provide side no longer has part of a file" when attempting to download. I removed the file again and ran `sendme get` again - it silently does not receive anything.

**Comment by rklaehn** [comment]
Thanks for the test. This is a bug, but nothing major. You get an error. It is even a very appropriate error, NotFound.

But currently we don't print that but just abort with a non 0 exit code. The fix is to just print something when getting this error. How is this:

![image](https://github.com/n0-computer/sendme/assets/248257/439b2392-6dd5-421c-9664-5115cd18fb25)

**Comment by rklaehn** [comment]
Should be fixed with the latest release
